# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["apriansyahramadhan123@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-default"
description = "idk"
language = "javascript"
manifest_version = 3
name = "Nymphaea"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"
